### ISSUE TITLE
what is 'tokenizer_bpe_model'

### ISSUE THREAD

**Issue by ai22453** [facebookresearch/av_hubert#11]
Hi
where is tokenizer_bpe_model for finetuning?

**Comment by chevalierNoir** [comment]
Hi,

It is the word tokenizer model. You can follow the step 4 in [LRS3 preprocessing](https://github.com/facebookresearch/av_hubert/tree/main/avhubert/preparation) to generate it.

**Comment by ai22453** [comment]
thank you so much.
