### ISSUE TITLE
sbatch error Invalid job array specification during "MUSAN data preparation"

### ISSUE THREAD

**Issue by YUCHEN005** [facebookresearch/av_hubert#14]
Hi authors, thank you for sharing such nice work!

I have downloaded the MUSAN dataset, and now try to do the data preparation. First I got the argument `slurm_partition` using command `scontrol show partition`, then I directly run the python command in the terminal, I met such issue:

> (avhubert) [huyuchen@ntu-sce-headnode preparation]$ python musan_prepare.py --musan /home3/huyuchen/raw_data/musan --nshard 4  --slurm_partition defq
Split raw audio
sbatch: error: Batch job submission failed: Invalid job array specification
subprocess.CalledProcessError: Command '['sbatch', '/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/preparation/tmphs_2jdk9/submission_file_147b1d1bf46b441aa7f60bca08a3f447.sh']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "musan_prepare.py", line 122, in <module>
    jobs = executor.map_array(split_musan, [args.musan for _ in ranks], ranks, [args.nshard for _ in ranks])
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/submitit/core/core.py", line 701, in map_array
    return self._internal_process_submissions(submissions)
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/submitit/auto/auto.py", line 218, in _internal_process_submissions
    return self._executor._internal_process_submissions(delayed_submissions)
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/submitit/slurm/slurm.py", line 332, in _internal_process_submissions
    first_job: core.Job[tp.Any] = array_ex._submit_command(self._submitit_command_str)
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/submitit/core/core.py", line 864, in _submit_command
    output = utils.CommandFunction(command_list, verbose=False)()  # explicit errors
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/submitit/core/utils.py", line 350, in __call__
    raise FailedJobError(stderr) from subprocess_error
submitit.core.utils.FailedJobError: sbatch: error: Batch job submission failed: Invalid job array specification

Alternately, I try to use slurm to run it, using command `sbatch -o 1.log submit_musan.sh`, where the `submit_musan.sh` looks like:

> #!/usr/bin/env bash
cmd="slurm.pl --quiet --nodelist=node03 --gpu 1 --num-threads 8"
source activate avhubert
$cmd log/1.log \
python musan_prepare.py --musan /home3/huyuchen/raw_data/musan --nshard 4  --slurm_partition defq

But same issue appears as above, can you help see what happened? Thank you!

**Comment by chevalierNoir** [comment]
Hi,

It's possible that the array size is larger than your max array size on slurm. Can you check `scontrol show config | grep MaxArraySize`?

**Comment by YUCHEN005** [comment]
> Hi,
> 
> It's possible that the array size is larger than your max array size on slurm. Can you check `scontrol show config | grep MaxArraySize`?

The MaxArraySize on slurm is 1001, so how to chage my array size to below 1001?

**Comment by YUCHEN005** [comment]
> > Hi,
> > It's possible that the array size is larger than your max array size on slurm. Can you check `scontrol show config | grep MaxArraySize`?
> 
> The MaxArraySize on slurm is 1001, so how to chage my array size to below 1001?

I make it works after setting nshard to 1, actually this step is very quick, so it's unnecessary to use parallel processing. Thank u.
