### ISSUE TITLE
Count number of frames per clip Problem

### ISSUE THREAD

**Issue by dinghongzhe1024** [facebookresearch/av_hubert#24]
for rank in $(seq 0 $((nshard - 1)));do cat ${lrs3}/nframes.audio.${rank}; done > ${lrs3}/nframes.audio
for rank in $(seq 0 $((nshard - 1)));do cat ${lrs3}/nframes.video.${rank}; done > ${lrs3}/nframes.video

Hello
Will these two lines of code actually work in the terminal?

**Comment by dinghongzhe1024** [comment]
I tried to run in terminal, but unfortunately, it failed

**Comment by chevalierNoir** [comment]
Hi,

What is the error?

**Comment by dinghongzhe1024** [comment]
for rank in $(seq 0 $(255));do cat /datadrive/lrs3/nframes.audio.1; done > /datadrive/lrs3/nframes.audio
Set nshard=256 rank=1 When I run the code I get the  
"255: command not found" I don't konw how to fix it
By the way , could you tell the default parameters of the nshard and rank?
Thank you very much!

**Comment by dinghongzhe1024** [comment]
Hello 
When I run 
python count_frames.py --root /datadrive/lrs3 --manifest /datadrive/lrs3/file.list --nshard 512 --rank 0
I get the information as follow:
"Some audio/video files not exist, see /datadrive/lrs3/missing.list.0"
I don't konw what happen, maybe nshard=512 is too large? I remember no such error when nshard=256
Also by running the code "nshard=512;lrs3=/datadrive/lrs3/;rank=0;for rank in $(seq 0 $((nshard - 1)));do cat ${lrs3}/nframes.audio.${rank}; done > ${lrs3}/nframes.audio"
I get result as follow:
"cat: /datadrive/lrs3//nframes.video.0: No such file or directory"
Thank you for your help...

**Comment by chevalierNoir** [comment]
The error "Some audio/video files not exist, see /datadrive/lrs3/missing.list.0" shows that some audio/videos have not been correctly generated. Make sure step 1 and 2 are complete before step 3. To simplify things, you can just set `nshard` to 1 and `rank` to 0 whenever they are used.

**Comment by dinghongzhe1024** [comment]
Hi, can you tell me the relationship between nshard and rank?
Are they rank=nshard-1 or something
I am using a Microsoft Azure server with 4 CPUs and 16G of RAM, what should I set the nshard and rank to?
Because I noticed that it takes too long to set nshard to 1 and rank to 0,
Hi, can you tell me the relationship between nshard and rank?
Are they rank=nshard-1 or something
I am using a Microsoft Azure server with 4 CPUs and 16G of RAM, what should I set the nshard and rank to?
Because I noticed that it takes too long to set nshard to 1 and rank to 0,
Thank you so much！

**Comment by dinghongzhe1024** [comment]
Thank you so so much!

**Comment by dinghongzhe1024** [comment]
python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 0 --nshard 4 --step 2 &
python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 1 --nshard 4 --step 2 &
python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 2 --nshard 4 --step 2 & 
python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 3 --nshard 4 --step 2 &
Does this mean that I can run the above code at the same time?
Thank you!

**Comment by chevalierNoir** [comment]
> python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 0 --nshard 4 --step 2 & python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 1 --nshard 4 --step 2 & python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 2 --nshard 4 --step 2 & python lrs3_prepare.py --lrs3 /datadrive/lrs3 --ffmpeg /usr/bin/ffmpeg --rank 3 --nshard 4 --step 2 & Does this mean that I can run the above code at the same time? Thank you!

Yes.

**Comment by dinghongzhe1024** [comment]
Thank you for your help! Now it's clear to me, thanks again for the guidance!
