### ISSUE TITLE
LRS3 data

### ISSUE THREAD

**Issue by zuujhyt** [facebookresearch/av_hubert#31]
Hi, I try to run the preprocessing part, may I ask the LRS3 data you use is the original youtube videos or the roughly cropped face data made by VGG team (the one needs a filled form for request)? or it doesnt matter which one to use? thanks

**Comment by chevalierNoir** [comment]
Hi, 

We use the video files (loosely cropped face region) [here](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs3.html),  which requires a request form.

**Comment by zuujhyt** [comment]
okay, thx.
