### ISSUE TITLE
Questions about pre-training an AV-HuBERT model.

### ISSUE THREAD

**Issue by jc-hou** [facebookresearch/av_hubert#32]
Hi, thanks for the work.
I was trying to understand your code to pre-train an AV-HuBERT model based on your readme instructions,
and I have a few simple questions.

(1) Is positional embedding not used during pre-training?
 In ```hubert.py```, neither ```conv_pos``` nor ```conv_pos_groups``` was used.
so the positional embedding was not used? if so, any reason?
(2) resent was not using a pre-trained one as a feature extractor during pre-training?
In ```hubert.py```:
```
        resnet = ResEncoder(relu_type=cfg.resnet_relu_type, weights=cfg.resnet_weights)
        self.feature_extractor_audio = SubModel(resnet=None, input_dim=cfg.audio_feat_dim, cfg=sub_cfg)
        self.feature_extractor_video = SubModel(resnet=resnet, input_dim=resnet.backend_out, cfg=sub_cfg)
```
It seems ```resnet_weights``` was not set in any config files, so the resnet would be trained from scratch in the pre-training phase, right?
I thought a resnet pretrained on ImageNet would be freezed and used as a feature extractor in this context, though I am not familiar with the literature.

Thanks in advance for your comment!

**Comment by chevalierNoir** [comment]
Hi,

1. Positional embedding is used in the model. See [here](https://github.com/pytorch/fairseq/blob/afc77bdf4bb51453ce76f1572ef2ee6ddcda8eeb/fairseq/models/wav2vec/wav2vec2.py#L824-L837).
2. The ResNet we use is not entirely same as the ResNet trained with ImageNet, as it has [3D-conv layers](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/resnet.py#L137-L141) in the front-end. Given the lip images are of different domain from ImageNet, directly using an ImageNet-pretrained model as feature extractor may also not be very helpful.

**Comment by jc-hou** [comment]
I understand, thank you very much for your reply.
