### ISSUE TITLE
nshard and rank argument

### ISSUE THREAD

**Issue by 18445864529** [facebookresearch/av_hubert#4]
First, thank you for your great work! One question w.r.t. the data preparation.
After reading the README of LRS3 preparation, I still didn't get what the `nshard` and `rank` arguments are, and what they are used for. What should the default values of them be if I just simply want to reproduce the results in the paper?

**Comment by chevalierNoir** [comment]
Hi, `nshard` and `rank` are used if you want to parallelize your processing. Suppose you want to detect facial landmark by running `python detect_face.py ... --shard <nshard> --rank <rank>`, then the the whole dataset will be divided into `nshard` parts and this particular job will detect facial landmark for `rank`th part. 

If you are are on a cluster, then launch `nshard` jobs with `rank` argument of each job being set to `0, 1, ... nshard-1`. If you are on a single machine and do not need parallelizing, simply putting `nshard` to 1 and `rank` to 0 will process all videos in one job.

**Comment by 18445864529** [comment]
Thank you for your explaination! Close this issue now.

**Comment by PussyCat0700** [comment]
> Hi, `nshard` and `rank` are used if you want to parallelize your processing. Suppose you want to detect facial landmark by running `python detect_face.py ... --shard <nshard> --rank <rank>`, then the the whole dataset will be divided into `nshard` parts and this particular job will detect facial landmark for `rank`th part.
> 
> If you are are on a cluster, then launch `nshard` jobs with `rank` argument of each job being set to `0, 1, ... nshard-1`. If you are on a single machine and do not need parallelizing, simply putting `nshard` to 1 and `rank` to 0 will process all videos in one job.

Great answer! That solves my problem again
