### ISSUE TITLE
[Easy Question] Sequence length

### ISSUE THREAD

**Issue by JuanFMontesinos** [facebookresearch/av_hubert#46]
Hi,
I was wondering what is the largest sequence the model can deal with and if fairseq pipeline can deal with automatic batching in case a sequence is larger than the max seq of the model. Namely, can I directly drop for example a 3-min video? or should I do chunks myself.

**Comment by chevalierNoir** [comment]
In principle, the input sequence can be arbitrarily long as long as it fits into the GPU memory. In training, we set the maximum sequence length to 20 second ([500 frames](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/conf/finetune/large_vox_30h.yaml#L37)). We also keep that length during inference. For a 3-min video, you can either chunk that into 20-second clips or feed longer clips by resetting the `task.max_sample_size` to a larger value.

**Comment by JuanFMontesinos** [comment]
Hi, thanks for the reply.
I was extracting visual features and, in that case, it works fine (although I'm wondering if passing larger sequences may affect the results) Using the full models for a 2500-sample sequence the results are weird
![imagen](https://user-images.githubusercontent.com/32466310/165555687-f9d52816-d99c-4398-9c7a-bac77b9f5962.png)
Meanwhile for a 8s sample it was working fine:
![imagen](https://user-images.githubusercontent.com/32466310/165555945-10b81dcf-ad5c-41b0-8570-0d9159868981.png)
