### ISSUE TITLE
Audio/Video data augmentation

### ISSUE THREAD

**Issue by YUCHEN005** [facebookresearch/av_hubert#49]
Hi Authors,

Thank you for good sharing. Since you have added noise on input speech with 0.25 probability, I wonder if you have deployed data augmentation on the input image? (like the image flip that CV community usually do) If yes, how can I use it on the avhubert? 

Thank you~

**Comment by chevalierNoir** [comment]
Hi,

Yes. We do data augmentation on images, including horizontal flipping and random cropping. You can find details [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_dataset.py#L216-L227).

**Comment by YUCHEN005** [comment]
See it, thank you~
