### ISSUE TITLE
Question about freeze-finetuning-updates

### ISSUE THREAD

**Issue by YadiraRoCa** [facebookresearch/av_hubert#52]
Hello, How does the hyperparameter freeze-finetuning-updates work? 
Thanks a lot in advance!

**Comment by chevalierNoir** [comment]
Hi,

Setting `freeze-finetuning-updates` to `n` will freeze the pre-trained encoder for `n` steps during fine-tuning. See [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_asr.py#L494-L496).

**Comment by YadiraRoCa** [comment]
Thank you for your answer!  
I am not familiar with this type of freezing. What are the advantages of freezing the entire encoder for n steps? 
Lastly, the **entire** pre-trained encoder is frozen for n steps, and then the rest of the steps are used to finetune the **entire** encoder, right?

**Comment by chevalierNoir** [comment]
In cases like low-resource regime, freezing the encoder for `n` steps sometimes achieve better performance than fine-tuning the whole model from the beginning. In steps after `n`, the entire model is fine-tuned.
