### ISSUE TITLE
model register problem with multiple pre-trained models

### ISSUE THREAD

**Issue by chrisole** [facebookresearch/av_hubert#55]
Hi,

Thanks for your wonderful work.

I want load multiple pre-trained model in the same task. But when I try to load another pre-trained model, a model registration bug is shown as following:

#
Traceback (most recent call last):
  File "hubert_asr.py", line 489, in load_vision_model
    model = task.build_model(cfg.model)
  File "/home3/chenchen/research/hubert/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home3/chenchen/research/hubert/fairseq/fairseq/models/__init__.py", line 89, in build_model
    assert model is not None, (
AssertionError: Could not infer model type from {'_name': 'av_hubert_seq2seq',.......,Available models: dict_keys(['wav2vec', 'wav2vec2', 'wav2vec_ctc', 'wav2vec_seq2seq', 'hubert', 'hubert_ctc', 'transformer_lm', 'av_hubert', 'av_hubert_ctc']) Requested model type: av_hubert_seq2seq.
#

I think it because the 'av_hubert_seq2seq' is not registered into the model list, and how can I add it?

Thanks!

**Comment by chevalierNoir** [comment]
Hi,

You can register the model by `fairseq.utils.import_user_module(argparse.Namespace(user_dir=user_dir))`. If you clone the repo to `/path/to/repo`, then `user_dir=/path/to/repo/avhubert`. You can find one example of usage in the **Import a pre-trained model** section of the [demo](https://github.com/facebookresearch/av_hubert#demo).

**Comment by chrisole** [comment]
Hi,

Thanks for your kindly reply.

I add the code “  utils.import_user_module(Namespace(user_dir='/path/to/repo/avhubert'))” with my own dir.

I realised that the task has been successfully registered, but now a new bug shown as following:

###
  File "/.../hubert/avhubert/__init__.py", line 7, in <module>
    from .hubert_asr import *  # noqa
  File "/.../hubert/avhubert/hubert_asr.py", line 27, in <module>
    from hubert import AVHubertModel
  File "/...hubert/avhubert/hubert.py", line 335, in <module>
    class AVHubertModel(BaseFairseqModel):
  File "/.../hubert/fairseq/fairseq/models/__init__.py", line 124, in register_model_cls
    raise ValueError("Cannot register duplicate model ({})".format(name))
ValueError: Cannot register duplicate model (av_hubert)
###

I don't know why the import_user_module function will register the same model (av_hubert) twice. How do you suggest for this?

Thanks~

**Comment by chevalierNoir** [comment]
Hi,

I think you didn't have argument in your running command? Just append some random argument to your command like `python run.py dummy` should fix the problem. For debugging purpose, we use no-argument as a special case which can lead to duplicate registration. See [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_asr.py#L24-L31).

**Comment by chrisole** [comment]
Hi, Thanks for you kindly reply. It is very helpful and I have address it.
