### ISSUE TITLE
problem with the skvideo library during the data preparation stage

### ISSUE THREAD

**Issue by qszhum** [facebookresearch/av_hubert#57]
Hello author, in the data processing stage, I found that the skvideo library will get stuck when reading long videos (longer than 6s), but it is fine when reading short videos. When I test the skvideo library alone, the long video can be read normally, I don't know where the problem is.
https://github.com/facebookresearch/av_hubert/blob/cd1fd24e71b18f5c1a7203aec6ce4479a61e7e67/avhubert/preparation/detect_landmark.py#L12

Test the skvideo library alone. Both ways work fine when tested individually.
```
import skvideo.io
import numpy as np
from tqdm import tqdm
import os, cv2

fids = [ln.strip() for ln in open("path/of/file.list").readlines()]

# def load_video(path):
#     videogen = skvideo.io.vread(path)
#     print("loaded")
#     frames = np.array([frame for frame in videogen])
#     return frames

def load_video(path):
    for i in range(3):
        try:
            cap = cv2.VideoCapture(path)
            frames = []
            while True:
                ret, frame = cap.read()
                if ret:
                    frames.append(frame)
                else:
                    break
            frames = np.stack(frames)
            return frames
        except Exception:
            print(f"failed loading {path} ({i} / 3)")
            if i == 2:
                raise ValueError(f"Unable to load {path}")


for fid in tqdm(fids):
    video_path = os.path.join("path/of/lsr3", fid+'.mp4')
    videogen = load_video(video_path)
    print(np.shape(videogen))
```

My solution now is to use another cv2 library to read the video, I am not sure if this will affect the final result, I would like to ask you for an answer. Thank you for your reply.
```
# def load_video(path):
#     videogen = skvideo.io.vread(path)
#     frames = np.array([frame for frame in videogen])
#     return frames

def load_video(path):
    for i in range(3):
        try:
            cap = cv2.VideoCapture(path)
            frames = []
            while True:
                ret, frame = cap.read()
                if ret:
                    frames.append(frame)
                else:
                    break
            frames = np.stack(frames)
            return frames
        except Exception:
            print(f"failed loading {path} ({i} / 3)")
            if i == 2:
                raise ValueError(f"Unable to load {path}")
```
Reference code from here.
https://github.com/facebookresearch/av_hubert/blob/cd1fd24e71b18f5c1a7203aec6ce4479a61e7e67/avhubert/utils.py#L13

**Comment by chevalierNoir** [comment]
Hi,

If you use cv2 to load the video, then convert image frame from BGR (cv2 default) to RGB (skvideo default) by `frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)`. I randomly tested 100 videos and the loaded data are exactly same.

**Comment by qszhum** [comment]
@chevalierNoir OK, I see, thanks for your reply.
