### ISSUE TITLE
'task.input_modality' is not used in the pre-training

### ISSUE THREAD

**Issue by qszhum** [facebookresearch/av_hubert#58]
Hi author, the parameter task.input_modality https://github.com/facebookresearch/av_hubert/blob/cd1fd24e71b18f5c1a7203aec6ce4479a61e7e67/avhubert/hubert.py#L67 is not used in pre-training, the correct parameter should be task.modalities https://github.com/facebookresearch/av_hubert/blob/cd1fd24e71b18f5c1a7203aec6ce4479a61e7e67/avhubert/hubert_pretraining.py#L150, right?  Thanks for your reply.

**Comment by chevalierNoir** [comment]
Hi,

That's correct. `task.input_modality` is a deprecated argument which is no longer used.
