### ISSUE TITLE
Can you open source extracted facial landmark?

### ISSUE THREAD

**Issue by qszhum** [facebookresearch/av_hubert#59]
Hi author, can you open source extracted facial landmark and aligned mouth? The VoxCeleb2 Preprocessing https://github.com/facebookresearch/av_hubert/tree/main/avhubert/preparation#voxceleb2-preprocessing tasks too much time.

**Comment by chevalierNoir** [comment]
Hi,

Unfortunately, we cannot release the extracted facial landmark data for the moment due to some potential privacy issues. You may consider parallelizing this process on a cluster.
