### ISSUE TITLE
How to find the English files in VoxCeleb2

### ISSUE THREAD

**Issue by joyolee** [facebookresearch/av_hubert#60]
Dear authors,

thank you for the great work! In this repo, you already provided a list of English files in Voxceleb2. I would ask, how did you get the list? Did you use a language recognition tool or there is a list for different languages in Voxceleb2 but I missed it? 

I'm looking forward to your reply.

Best regards,
Zhengyang

**Comment by chevalierNoir** [comment]
Hi,

We use a simple heuristic to choose the English utterances of VoxCeleb2. Specifically, we use an off-the-shelf character-based ASR model to transcribe each utterance and count its proportion of valid English words.  An utterance is selected if the proportion of valid English words is higher than 60%. You can find more details in section B.1 of [the paper](https://arxiv.org/pdf/2201.02184.pdf).

**Comment by joyolee** [comment]
> Hi,
> 
> We use a simple heuristic to choose the English utterances of VoxCeleb2. Specifically, we use an off-the-shelf character-based ASR model to transcribe each utterance and count its proportion of valid English words. An utterance is selected if the proportion of valid English words is higher than 60%. You can find more details in section B.1 of [the paper](https://arxiv.org/pdf/2201.02184.pdf).

Thanks a lot! Now I'm clear about it!
