### ISSUE TITLE
How to only perform test?

### ISSUE THREAD

**Issue by BDHU** [facebookresearch/av_hubert#68]
I only want to use the checkpoint on test set without all the preprocessing on training set. Is there an easy way to achieve this, and not go through time-consuming preprocessing for all data? Thanks!

**Comment by chevalierNoir** [comment]
Hi,

Yes. You have two ways of doing this. First you can use [this decoding command](https://github.com/facebookresearch/av_hubert#seq2seq-decoding). In this case, you should at least prepare the`test.tsv` and `test.wrd` files. Second way (maybe simpler) is to follow the example of inference in the [demo](https://colab.research.google.com/drive/1bNXkfpHiVHzXQH8WjGhzQ-fsDxolpUjD). 

On the other hand, if you want to prepare data for test only, you can accelerate the data preprocessing by setting some dummy paths to the `pretrain` and `trainval` partitions of LRS3 by just keeping a few (say ~10) examples in them.

**Comment by BDHU** [comment]
Thanks!

**Comment by ozgemercanoglu** [comment]
Hi, I am trying the demo, but getting the following error in line: 
models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task([cfg.common_eval.path])

```
 task = tasks.setup_task(cfg.task)
  File "/home/om0009/miniconda3/envs/avhubert/lib/python3.8/site-packages/fairseq/tasks/__init__.py", line 42, in setup_task
    assert (
AssertionError: Could not infer task type from {'_name': 'av_hubert_pretraining', 'data': '/checkpoint/bshi/data/lrs3//avsvox/en-vox-multimodal-tsv/', 'label_dir': '/checkpoint/bshi/data/lrs3//video/hubert/stitch-iters/envox-iter4-l12c2000/', 'labels': ['km'], 'label_rate': 25, 'sample_rate': 25, 'max_sample_size': 2000, 'min_sample_size': 5, 'pad_audio': False, 'random_crop': True, 'normalize': True, 'input_modality': 'image', 'image_aug': True, 'stack_order_audio': 4, 'max_trim_sample_size': 400, 'fine_tuning': False}. Available tasks: dict_keys(['translation', 'translation_from_pretrained_xlm', 'hubert_pretraining', 'cross_lingual_lm', 'translation_lev', 'speech_to_text', 'denoising', 'multilingual_denoising', 'audio_pretraining', 'sentence_prediction', 'translation_multi_simple_epoch', 'sentence_ranking', 'simul_speech_to_text', 'simul_text_to_text', 'online_backtranslation', 'legacy_masked_lm', 'multilingual_translation', 'semisupervised_translation', 'language_modeling', 'masked_lm', 'translation_from_pretrained_bart', 'multilingual_masked_lm', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt'])
```

On the other hand, I  also tried infer_s2s.py. It got the same error.
```
python -B infer_s2s.py --config-dir ./conf/ --config-name s2s_decode.yaml \
  dataset.gen_subset=test common_eval.path=/home/om0009/av_hubert/checkpoints/base_vox_iter5.pt \
  common_eval.results_path=/home/om0009/av_hubert/results \
  override.modalities=['video'] common.user_dir=./ \
  +override.data=/home/om0009/av_hubert/avhubert/preparation/data +override.label_dir=/home/om0009/av_hubert/avhubert/preparation/data
```

In the setup_task() function, task is None, so it causes this issue. Is there anyone else faced with the same problem? Thanks!
