### ISSUE TITLE
Error in step 2 of preprocessing, what values to put in ${rank} and ${nshard}

### ISSUE THREAD

**Issue by JeetShah25** [facebookresearch/av_hubert#77]
Hi authors,
Great work! 
Could you please help with the values of {rank} and {nshard}? 
When putting {rank} as 5 and {nshard} as 6, I am getting the following error, would be really grateful if you could help me out with it!

>python lrs3_prepare.py --lrs3 data --ffmpeg /path/to/ffmpeg --rank 5 --nshard 6 --step 2
Trim original videos in pretrain
Step 2. Trim video and audio
Total videos in current shard: 6363/38198
  0%|                                                                                                                                                                                    | 0/6363 [00:00<?, ?it/s]The system cannot find the path specified.
  0%|                                                                                                                                                                                    | 0/6363 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "lrs3_prepare.py", line 235, in <module>
    trim_pretrain(args.lrs3, args.ffmpeg, args.rank, args.nshard, step=args.step)
  File "lrs3_prepare.py", line 179, in trim_pretrain
    trim_video_frame(csv_fn, pretrain_dir, output_video_dir, ffmpeg, rank, nshard)
  File "lrs3_prepare.py", line 127, in trim_video_frame
    pipe = subprocess.call(cmd, stdout = subprocess.PIPE, stderr = subprocess.STDOUT) # subprocess.PIPE
  File "D:\Users\jeet\Anaconda3\envs\avhubert\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Users\jeet\Anaconda3\envs\avhubert\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Users\jeet\Anaconda3\envs\avhubert\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by chevalierNoir** [comment]
Hi,

Can you remove `-loglevel quiet` in line 110 and 125 of [`lrs3_prepare.py`](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/preparation/lrs3_prepare.py) and see what the error is?

**Comment by JeetShah25** [comment]
Hey,

I removed -loglevel quiet as you mentioned above, the error is the same I mentioned while describing the issue

**Comment by chevalierNoir** [comment]
I suspect this is an issue of missing data. Could you try running the two commands manually (line 110 and 125) for the example that doesn't work?

**Comment by JeetShah25** [comment]
Hey, 
I feel the error is in due to the subprocess function in lrs3_prepare.py, could you help me with the excepted output when we print cmd of line 156 in lrs_prepare.py
Thank you!

**Comment by chevalierNoir** [comment]
If it runs normally, there should be some ffmpeg processing information printed out assuming the `-loglevel quiet` is commented out.
