### ISSUE TITLE
non-deterministic results when decoding with noises

### ISSUE THREAD

**Issue by joyolee** [facebookresearch/av_hubert#78]
Dear authors, 

thanks a lot for your excellent work. I would ask if your results are deterministic when decoding with noises, e.g. babble noise.
In my experiments, the noise probability is set as 1 during decoding. I find that the decoding results are not deterministic when running multiple times. The difference can be larger than 1%.

I find the reason could be the random seed when selecting noises:
https://github.com/facebookresearch/av_hubert/blob/5ab235b3d9dac548055670d534b283b5b70212cc/avhubert/hubert_dataset.py#L305

I would ask, do you have the same observation? If so, how did you solve the non-deterministic problem?

I'm looking forward to your reply!

Merry Christmas and best regards,
Zhengyang

**Comment by chevalierNoir** [comment]
Hi Zhengyang,

Merry Christmas. Yes, we also observed that there is some randomness in the result per run. The WER averaged across noise SNR/types is usually more stable. Also as we tune the decoding hyperparameters (e.g., beam size) on the valid set, the test WER is generally stable. Another way to reduce the randomness is to have multiple runs and report the mean WER.

**Comment by joyolee** [comment]
> Hi Zhengyang,
> 
> Merry Christmas. Yes, we also observed that there is some randomness in the result per run. The WER averaged across noise SNR/types is usually more stable. Also as we tune the decoding hyperparameters (e.g., beam size) on the valid set, the test WER is generally stable. Another way to reduce the randomness is to have multiple runs and report the mean WER.

Hi, thanks a lot! Averaging the WER of multiple runs is also the method that we use. The average WER is relatively stable.

**Comment by Rongjiehuang** [comment]
Hi, could you please tell me what the noise directory looks like? After data preparation, we have `all, babble, music and noise` directories under `musan/tsv/`, while I could not find the `speech` directory mentioned in this work.

**Comment by chevalierNoir** [comment]
> Hi, could you please tell me what the noise directory looks like? After data preparation, we have `all, babble, music and noise` directories under `musan/tsv/`, while I could not find the `speech` directory mentioned in this work.

Please find how to set up `speech` directory [here](https://github.com/facebookresearch/av_hubert/tree/main/avhubert/preparation#2-lrs3-audio-noise-preparation).

**Comment by nastia-lado** [comment]
Hi, @joyolee!

If I understood correctly, you used AVSR model for decoding in noisy conditions.
Did you use colab by any chance?
I'm trying to modify the colab example to work with AVSR model (the example is only for VSR), but the colab crashes for unknown reasons. I'm trying to understand whether it's only my problem.
