### ISSUE TITLE
How to finetune on AVSR setting?

### ISSUE THREAD

**Issue by PussyCat0700** [facebookresearch/av_hubert#80]
Hi Noir:

I am wondering how I should finetune under AVSR settings using model weights available on your [checkpoint release website](https://facebookresearch.github.io/av_hubert/). If I finetune **base_lrs3_iter5.pt** on both audio and visual modality with base_lrs3_30h.yaml, I can **decode with both video and audio modality** to get an WER of **6.05%** and it seems that the performance can still be improved, especially compared with your performance with just audio modality in table 4 of your essay, where you **decoded with only audio modality** and got 5.4% for A/MFCC→A and 4.9% for A/MFCC→AV under 433h/30h base setting. So your ASR performance is actually a lot better than my AVSR performance and I think something is up with my hyperparameters or something.

Any advice about AVSR finetuning? Thanks very much for any advice/help you provide!

**Comment by chevalierNoir** [comment]
Hi,

I think you can get performance boost by tuning hyperparameters for this setting. The config `base_lrs3_30h.yaml` is for video-only and thus may not be optimal for AVSR. For AVSR, you can tune hyperparameters such as `freeze_finetune_updates` and `max_update`, as well as `beam` and `lenpen` for decoding.

**Comment by PussyCat0700** [comment]
> Hi,
> 
> I think you can get performance boost by tuning hyperparameters for this setting. The config `base_lrs3_30h.yaml` is for video-only and thus may not be optimal for AVSR. For AVSR, you can tune hyperparameters such as `freeze_finetune_updates` and `max_update`, as well as `beam` and `lenpen` for decoding.

Hi Noir,

Thanks very much for your reply! Are there any configurations for AVSR that I can refer to?

**Comment by chevalierNoir** [comment]
> > Hi,
> > I think you can get performance boost by tuning hyperparameters for this setting. The config `base_lrs3_30h.yaml` is for video-only and thus may not be optimal for AVSR. For AVSR, you can tune hyperparameters such as `freeze_finetune_updates` and `max_update`, as well as `beam` and `lenpen` for decoding.
> 
> Hi Noir,
> 
> Thanks very much for your reply! Are there any configurations for AVSR that I can refer to?

[This](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/conf/av-finetune/base_noise_pt_noise_ft_30h.yaml) is one fine-tuning config for AVSR.
