### ISSUE TITLE
How to decode without any label files

### ISSUE THREAD

**Issue by xinluyu1** [facebookresearch/av_hubert#88]
Hi , I am wandering if there's way decoding files without giving label files?

**Comment by PussyCat0700** [comment]
You can just get rid of anything related to labels in infer_s2s.py. In more detail, as long as you make sure this line is working and you shall decode without any ground truth labels:

https://github.com/facebookresearch/av_hubert/blob/5ab235b3d9dac548055670d534b283b5b70212cc/avhubert/infer_s2s.py#L221

**Comment by xinluyu1** [comment]
Great, thanks
