### ISSUE TITLE
Batch normalization with ResNet encoder on 0-padded videos

### ISSUE THREAD

**Issue by roudimit** [facebookresearch/av_hubert#93]
Hi, thanks for the great work and resources!
The video ResNet encoder merges the batch and sequence dimension so that the input to the 2D ResNet is a batch of images. https://github.com/facebookresearch/av_hubert/blob/5ab235b3d9dac548055670d534b283b5b70212cc/avhubert/resnet.py#L160
I think some of those images could correspond to 0-padding in the original video input, since the videos have different lengths and are 0 padded to the longest video length in the batch.
However, the images corresponding to the 0-padding would influence the batch normalization statistics.
I wonder if you have considered this / had any issue with it?
It seems that this would not be a big problem if the inputs in the batch are of similar length so that there is little 0 padding.

**Comment by wnhsu** [comment]
Hi, thanks for noting that. Indeed fairseq batch sequences of similar lengths so I think the issue was minimized. We didn't observe any problems so far but we haven't verified the delta either.

**Comment by roudimit** [comment]
Thanks, that makes sense.
